### PR TITLE
Include examples in command descriptor

### PR DESCRIPTION
**Pull request by tannerwelsh**
For supporting https://github.com/LearnersGuild/game-cli/issues/6

New output:

```
cmd - test command

Usage:
    cmd [options] <argument>

Commands:
    cmd1 - desc1
    cmd2 - desc2

Options:
    --first, -f           first option
    --second, -s          second option
    --help, -h            print usage information

Examples:
    // run command 1 with flag
    cmd1 -f

    // run command 2 with arguments
    cmd2 foo bar
```

### CODE REVIEW

**Comment by tannerwelsh** [comment]
@jeffreywescott mind giving this a peek & merge?

**Comment by jeffreywescott** [comment]
@tannerwelsh: I like this change. However, it seems to me that, when _rendering_ the examples, we should render the parent command name, too.

Also, I think it might be better for the example descriptions to be rendered prefixed with a `#` rather than `//`, since most users of the `subcli` module will likely be using it in a "shell" environment.

 So, instead of:

```
Examples:
    // run command 1 with flag
    cmd1 -f

    // run command 2 with arguments
    cmd2 foo bar
```

... we would have ...

```
Examples:
    # run command 1 with flag
    cmd cmd1 -f

    # run command 2 with arguments
    cmd cmd2 foo bar
```

WDYT?

**Comment by bundacia** [comment]
This may be over-engineering, but maybe we should make the prefix (`#` or `/`) something that you can set by passing in an optional third param to parse. I think for beginners if the usage shows a `#` they're going to try and type it.

**Comment by jeffreywescott** [comment]
@bundacia you may be right. But maybe we should "wait and see" if the examples confuse people before adding another feature?

**Comment by jeffreywescott** [comment]
Reassigning back to you, @tannerwelsh.

**Comment by bundacia** [comment]
@jeffreywescott yeah, that makes sense. Though if we're going to hard code for a single client environment shouldn't we hard code for the client we have and use the `/`?

**Comment by bundacia** [comment]
oh, fooey, nevermind. I thought we were using the `#` or `/` as the first part of the command, like the shell prompt or the "slash". Now I see that it was just a comment. Sheesh. Sorry folks. `#` is great.

**Comment by tannerwelsh** [comment]
Thanks folks. Updates made, ready to merge.

Side-note: using `#` for comments is great except that if we want to use Markdown formatting. :/ Probs not too likely in near future though.

**Pull request merged**
